lang: es
quarto-required: ">= 1.8"

engine: julia

format:
  html:
    html-dependencies:
    - name: plotly
      src: https://cdn.plot.ly/plotly-latest.min.js
    theme: simplex
    code-tools: true
    echo: true

execute:
  freeze: auto

project:
  type: website
  output-dir: docs
  
website:
  title: "Curso Introductorio a Julia y Recuperaci贸n de Informaci贸n"
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: 01-intro.qmd
        text: Introducci贸n al lenguaje Julia
      - href: 02-data-vis.qmd
        text: Uso de dataframes y visualizaci贸n

  # Add a footer to the website
  page-footer:
    left: "Eric S. Tellez"
    center: "Built with [Quarto](https://quarto.org/)"
